/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios/index'
import { Route as PreferencesIndexRouteImport } from './routes/preferences/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ActorsIndexRouteImport } from './routes/actors/index'
import { Route as ScenariosIdIndexRouteImport } from './routes/scenarios/$id/index'
import { Route as NotesIdIndexRouteImport } from './routes/notes/$id/index'
import { Route as ChatIdIndexRouteImport } from './routes/chat/$id/index'
import { Route as ActorsIdIndexRouteImport } from './routes/actors/$id/index'
import { Route as PreferencesLlmConfigsIdIndexRouteImport } from './routes/preferences/llm-configs/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/preferences/',
  path: '/preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIndexRoute = ActorsIndexRouteImport.update({
  id: '/actors/',
  path: '/actors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIdIndexRoute = ScenariosIdIndexRouteImport.update({
  id: '/scenarios/$id/',
  path: '/scenarios/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdIndexRoute = NotesIdIndexRouteImport.update({
  id: '/notes/$id/',
  path: '/notes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdIndexRoute = ChatIdIndexRouteImport.update({
  id: '/chat/$id/',
  path: '/chat/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIdIndexRoute = ActorsIdIndexRouteImport.update({
  id: '/actors/$id/',
  path: '/actors/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesLlmConfigsIdIndexRoute =
  PreferencesLlmConfigsIdIndexRouteImport.update({
    id: '/preferences/llm-configs/$id/',
    path: '/preferences/llm-configs/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actors/': typeof ActorsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/home/': typeof HomeIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/actors/$id/': typeof ActorsIdIndexRoute
  '/chat/$id/': typeof ChatIdIndexRoute
  '/notes/$id/': typeof NotesIdIndexRoute
  '/scenarios/$id/': typeof ScenariosIdIndexRoute
  '/preferences/llm-configs/$id/': typeof PreferencesLlmConfigsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actors': typeof ActorsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/home': typeof HomeIndexRoute
  '/notes': typeof NotesIndexRoute
  '/preferences': typeof PreferencesIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/actors/$id': typeof ActorsIdIndexRoute
  '/chat/$id': typeof ChatIdIndexRoute
  '/notes/$id': typeof NotesIdIndexRoute
  '/scenarios/$id': typeof ScenariosIdIndexRoute
  '/preferences/llm-configs/$id': typeof PreferencesLlmConfigsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actors/': typeof ActorsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/home/': typeof HomeIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/actors/$id/': typeof ActorsIdIndexRoute
  '/chat/$id/': typeof ChatIdIndexRoute
  '/notes/$id/': typeof NotesIdIndexRoute
  '/scenarios/$id/': typeof ScenariosIdIndexRoute
  '/preferences/llm-configs/$id/': typeof PreferencesLlmConfigsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actors/'
    | '/chat/'
    | '/home/'
    | '/notes/'
    | '/preferences/'
    | '/scenarios/'
    | '/actors/$id/'
    | '/chat/$id/'
    | '/notes/$id/'
    | '/scenarios/$id/'
    | '/preferences/llm-configs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actors'
    | '/chat'
    | '/home'
    | '/notes'
    | '/preferences'
    | '/scenarios'
    | '/actors/$id'
    | '/chat/$id'
    | '/notes/$id'
    | '/scenarios/$id'
    | '/preferences/llm-configs/$id'
  id:
    | '__root__'
    | '/'
    | '/actors/'
    | '/chat/'
    | '/home/'
    | '/notes/'
    | '/preferences/'
    | '/scenarios/'
    | '/actors/$id/'
    | '/chat/$id/'
    | '/notes/$id/'
    | '/scenarios/$id/'
    | '/preferences/llm-configs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorsIndexRoute: typeof ActorsIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  ActorsIdIndexRoute: typeof ActorsIdIndexRoute
  ChatIdIndexRoute: typeof ChatIdIndexRoute
  NotesIdIndexRoute: typeof NotesIdIndexRoute
  ScenariosIdIndexRoute: typeof ScenariosIdIndexRoute
  PreferencesLlmConfigsIdIndexRoute: typeof PreferencesLlmConfigsIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/preferences'
      fullPath: '/preferences/'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/': {
      id: '/actors/'
      path: '/actors'
      fullPath: '/actors/'
      preLoaderRoute: typeof ActorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$id/': {
      id: '/scenarios/$id/'
      path: '/scenarios/$id'
      fullPath: '/scenarios/$id/'
      preLoaderRoute: typeof ScenariosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id/': {
      id: '/notes/$id/'
      path: '/notes/$id'
      fullPath: '/notes/$id/'
      preLoaderRoute: typeof NotesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id/': {
      id: '/chat/$id/'
      path: '/chat/$id'
      fullPath: '/chat/$id/'
      preLoaderRoute: typeof ChatIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/$id/': {
      id: '/actors/$id/'
      path: '/actors/$id'
      fullPath: '/actors/$id/'
      preLoaderRoute: typeof ActorsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/llm-configs/$id/': {
      id: '/preferences/llm-configs/$id/'
      path: '/preferences/llm-configs/$id'
      fullPath: '/preferences/llm-configs/$id/'
      preLoaderRoute: typeof PreferencesLlmConfigsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorsIndexRoute: ActorsIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  ActorsIdIndexRoute: ActorsIdIndexRoute,
  ChatIdIndexRoute: ChatIdIndexRoute,
  NotesIdIndexRoute: NotesIdIndexRoute,
  ScenariosIdIndexRoute: ScenariosIdIndexRoute,
  PreferencesLlmConfigsIdIndexRoute: PreferencesLlmConfigsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
